[build]
  publish = "."
  command = "echo 'No build needed'"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/firebase-service-account.json"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

